image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: C:\Python27
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python35
    - PYTHON: C:\Python35-x64
    - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python37
    - PYTHON: C:\Python37-x64
    - PYTHON: C:\Python38
    - PYTHON: C:\Python38-x64
    - PYTHON: C:\Python39
    - PYTHON: C:\Python39-x64

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade setuptools wheel
  - python -m pip install --upgrade --editable .[tests]

build: off

test_script:
  - python -m pytest

after_test:
  - python setup.py sdist bdist_wheel

artifacts:
  - path: dist\*
