language: python

dist: xenial

matrix:
  include:
    - os: linux
      python: 2.7
      env: TOXENV=py27
    - os: linux
      python: 3.5
      env: TOXENV=py35
    - os: linux
      python: 3.6
      env: TOXENV=py36
    - os: linux
      python: 3.7
      env: TOXENV=py37
    - os: osx
      language: generic
      env: TOXENV=py27
    - os: osx
      language: generic
      env: TOXENV=py35
    - os: osx
      language: generic
      env: TOXENV=py36
    - os: osx
      language: generic
      env: TOXENV=py37

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python &>/dev/null || brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python3 &>/dev/null || brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv; fi

script:
  - python setup.py tests
