dist: focal  # https://docs.travis-ci.com/user/reference/linux
language: python

os: osx
osx_image: xcode12.2  # https://docs.travis-ci.com/user/reference/osx/#macos-version

jobs:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8
    - os: linux
      python: 3.9
    - os: osx
      language: shell
      env: PYTHON=2.7.18
    - os: osx
      language: shell
      env: PYTHON=3.5.10
    - os: osx
      language: shell
      env: PYTHON=3.6.12
    - os: osx
      language: shell
      env: PYTHON=3.7.9
    - os: osx
      language: shell
      env: PYTHON=3.8.7
    - os: osx
      language: shell
      env: PYTHON=3.9.1

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update
      brew outdated pyenv || brew upgrade pyenv
      pyenv --version
      echo "Available Python versions:"
      pyenv install --list | grep "^\s*\d"
      pyenv install $PYTHON
      export PYENV_VERSION=$PYTHON
      export PATH="/Users/travis/.pyenv/versions/$PYTHON/bin:$PATH"
    fi

install:
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade setuptools wheel
  - python -m pip install --upgrade --editable .[tests]

script:
  - python -m pytest
