language: python

dist: xenial

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: osx
      language: generic
      env: PYTHON=2.7.16
    - os: osx
      language: generic
      env: PYTHON=3.5.7
    - os: osx
      language: generic
      env: PYTHON=3.6.9
    - os: osx
      language: generic
      env: PYTHON=3.7.4

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew outdated pyenv || brew upgrade pyenv
      brew install pyenv-virtualenv
      pyenv install $PYTHON
      export PYENV_VERSION=$PYTHON
      pyenv virtualenv venv
      source /Users/travis/.pyenv/versions/${PYTHON}/envs/venv/bin/activate
    fi

install:
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade setuptools wheel

script:
  - python setup.py tests
