name: Tests

on: [push, pull_request]

env:
  PY_COLORS: 1
  COLUMNS: 110
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [windows-latest, ubuntu-20.04, macos-13]
        architecture: [x64, x86]
        exclude:
          - os: ubuntu-20.04
            architecture: x86
          - os: macos-13
            architecture: x86

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }} (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Set up Python ${{ matrix.python-version }} (non Windows)
        if: ${{ matrix.os != 'windows-latest' }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install locales (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y language-pack-en language-pack-de

      - name: Install pip, setuptools and wheel
        if: ${{ matrix.python-version != '3.5' }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel

      - name: Install numpy and scipy from cgohlke repo (x86, 3.10)
        if: ${{ matrix.architecture == 'x86' && matrix.python-version == '3.10' }}
        run: |
          pip install https://github.com/cgohlke/numpy-mkl-wheels/releases/download/v2024.1.3/numpy-1.26.3-cp310-cp310-win32.whl
          pip install https://github.com/cgohlke/numpy-mkl-wheels/releases/download/v2024.1.3/SciPy-1.11.4-cp310-cp310-win32.whl

      - name: Install numpy and scipy from cgohlke repo (x86, 3.11)
        if: ${{ matrix.architecture == 'x86' && matrix.python-version == '3.11' }}
        run: |
          pip install https://github.com/cgohlke/numpy-mkl-wheels/releases/download/v2024.1.3/numpy-1.26.3-cp311-cp311-win32.whl
          pip install https://github.com/cgohlke/numpy-mkl-wheels/releases/download/v2024.1.3/SciPy-1.11.4-cp311-cp311-win32.whl

      - name: Install numpy and scipy from cgohlke repo (x86, 3.12)
        if: ${{ matrix.architecture == 'x86' && matrix.python-version == '3.12' }}
        run: |
          pip install https://github.com/cgohlke/numpy-mkl-wheels/releases/download/v2024.1.3/numpy-1.26.3-cp312-cp312-win32.whl
          pip install https://github.com/cgohlke/numpy-mkl-wheels/releases/download/v2024.1.3/SciPy-1.11.4-cp312-cp312-win32.whl

      - name: Install package
        run: python -m pip install --upgrade --prefer-binary --editable .[tests]

      - name: Run tests
        run: python -m pytest
