name: Tests

on: [push, pull_request]

env:
  PY_COLORS: 1
  COLUMNS: 110

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [windows, ubuntu, macos]
        architecture: [x64, x86]
        exclude:
          - os: ubuntu
            architecture: x86
          - os: macos
            architecture: x86

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install locales (Ubuntu)
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y language-pack-en language-pack-de

      - name: Set up Python ${{ matrix.python-version }} (Windows)
        if: ${{ matrix.os == 'windows' }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Set up Python ${{ matrix.python-version }} (non Windows)
        if: ${{ matrix.os != 'windows' }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install numpy and scipy from cgohlke repo (x86, 3.10)
        if: ${{ matrix.architecture == 'x86' && matrix.python-version == '3.10' }}
        run: |
          pip install https://github.com/cgohlke/numpy-mkl-wheels/releases/download/v2024.1.3/numpy-1.26.3-cp310-cp310-win32.whl
          pip install https://github.com/cgohlke/numpy-mkl-wheels/releases/download/v2024.1.3/SciPy-1.11.4-cp310-cp310-win32.whl

      - name: Install numpy and scipy from cgohlke repo (x86, 3.11)
        if: ${{ matrix.architecture == 'x86' && matrix.python-version == '3.11' }}
        run: |
          pip install https://github.com/cgohlke/numpy-mkl-wheels/releases/download/v2024.1.3/numpy-1.26.3-cp311-cp311-win32.whl
          pip install https://github.com/cgohlke/numpy-mkl-wheels/releases/download/v2024.1.3/SciPy-1.11.4-cp311-cp311-win32.whl

      - name: Install numpy and scipy from cgohlke repo (x86, 3.12)
        if: ${{ matrix.architecture == 'x86' && matrix.python-version == '3.12' }}
        run: |
          pip install https://github.com/cgohlke/numpy-mkl-wheels/releases/download/v2024.1.3/numpy-1.26.3-cp312-cp312-win32.whl
          pip install https://github.com/cgohlke/numpy-mkl-wheels/releases/download/v2024.1.3/SciPy-1.11.4-cp312-cp312-win32.whl

      - name: Install lxml from source (macos, 3.8)
        if: ${{ matrix.os == 'macos' && matrix.python-version == '3.8' }}
        run: pip install --no-binary=lxml lxml

      - name: Install GTC (with test dependencies)
        run: python -m pip install --upgrade --prefer-binary --editable .[tests]

      - name: Run tests
        run: python -m pytest
